#!/bin/bash

CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --do_train \
    --overwrite_cache \
    --overwrite_output_dir \
    --flash_attn True \
    --use_unsloth True \
    --model_name_or_path models/seallm-7b-v2.5 \
    --dataset sft_qa_llm \
    --dataset_dir data \
    --template seallm \
    --finetuning_type lora \
    --lora_alpha 32\
    --lora_dropout 0.05 \
    --lora_target q_proj,v_proj \
    --output_dir saves/seallm-7b-v2.5/lora/sft \
    --cutoff_len 2048 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --weight_decay 0.1 \
    --logging_steps 10 \
    --warmup_steps 20 \
    --save_steps 100 \
    --eval_steps 100 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --learning_rate 1e-6 \
    --num_train_epochs 2.0 \
    --val_size 0.001 \
    --plot_loss \
    --bf16
